version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
  app:
    image: my-python-app
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
